version: '3.3'
services:
  php-apache:
    image: 'webdevops/php-apache:7.4'
    volumes:
      - './:/app'
    networks:
      - app-network
    ports:
      - "801:80"
    environment:
      - php.session.gc_maxlifetime=31536000
      - php.session.cookie_lifetime=31536000
      - php.memory_limit=2048M
      - PHP_DISPLAY_ERRORS=1
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mypass
    volumes:
      - ./dockre-compose/mysql:/docker-entrypoint-initdb.d
      - ./dockre-compose/dbdata:/var/lib/mysql
    networks:
      - app-network
  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin:latest'
    depends_on:
      - mysql
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=mypass
    networks:
      - app-network
    ports:
      - "802:80"
networks:
  app-network:
    driver: bridge
